version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todopassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-network

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    networks:
      - todo-network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - todo-network

volumes:
  mysql_data:

networks:
  todo-network:
