version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todopassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-network
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./backend
        target: /app
      - type: volume
        source: backend_node_modules
        target: /app/node_modules
    depends_on:
      - mysql
    networks:
      - todo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - type: volume
        source: frontend_node_modules
        target: /app/node_modules
    depends_on:
      - backend
    networks:
      - todo-network

volumes:
  mysql_data:
  backend_node_modules:
  frontend_node_modules:

networks:
  todo-network:
