version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todopassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8081:8080"
    environment:
      DB_HOST: mysql
      DB_USER: todo_user
      DB_PASSWORD: todopassword
      DB_NAME: todo_app
    depends_on:
      - mysql
    networks:
      - todo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - todo-network

volumes:
  mysql_data:

networks:
  todo-network:
